
defaults:
  - _self_
  - model: vit

_target_: tvp.pl_module.image_classifier.ImageClassifier
x_key: ${conventions.x_key}
y_key: ${conventions.y_key}
encoder: ??
classifier: ??

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-5
  # _target_: torch.optim.SGD
  # lr: 0.1
  # momentum: 0.9
  # weight_decay: 1e-1

# KEEP THIS COMMENTED OUT, it is handled in autoexperiment
# lr_scheduler:
#   # NOTE in case of multiple lr schedulers, to keep compatibility with current code, cosine annealing lr scheduler should be the first one
#   _target_: tvp.modules.cosine_annealing_lr_scheduler.CosineAnnealingLRScheduler
#   warmup_length: 200
#   total_steps: -42 # this is a placeholder, it will be set by the lightning module as the number of training steps
